# Generated by Django 6.0 on 2026-01-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_text', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('SUMMARIZE', 'Summarize'), ('PRIORITIZE', 'Auto Prioritize'), ('SUGGEST', 'Task Suggestion'), ('RISK', 'Risk Analysis'), ('GENERATE', 'Content Generation')], max_length=20)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
