# Generated by Django 6.0 on 2026-01-06 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='background_color',
            field=models.CharField(default='#0079BF', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
