# Generated by Django 6.0 on 2026-01-06 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='issue_type',
            field=models.CharField(choices=[('EPIC', 'Epic'), ('STORY', 'User Story'), ('TASK', 'Task'), ('BUG', 'Bug'), ('FEATURE', 'Feature Request')], default='TASK', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
