# Generated by Django 6.0 on 2026-01-07 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_task_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('is_released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SprintRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('went_well', models.TextField(help_text='What went well during the sprint?')),
                ('could_be_improved', models.TextField(help_text='What could be improved?')),
                ('action_items', models.TextField(help_text='Actions for the next sprint.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='projects.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('story_points', models.IntegerField(null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.task')),
            ],
        ),
        migrations.CreateModel(
            name='SprintCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('days_off', models.IntegerField(default=0)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='projects.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sprint', 'user')},
            },
        ),
    ]
