# Generated by Django 6.0 on 2026-01-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_task_tags'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='projects.tag'),
        ),
    ]
