# Generated by Django 6.0 on 2026-01-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('STATUS', 'Status Automation'), ('ASSIGNMENT', 'Assignment Automation'), ('NOTIFICATION', 'Notification Automation'), ('SLA', 'SLA Automation'), ('WORKFLOW', 'Workflow Automation')], max_length=30)),
                ('config_template', models.JSONField(help_text='JSON template for automation config')),
                ('is_system', models.BooleanField(default=False, help_text='System-provided template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('REPORT_GENERATION', 'Report Generation'), ('DATA_EXPORT', 'Data Export'), ('BULK_UPDATE', 'Bulk Update'), ('EMAIL_BATCH', 'Email Batch'), ('SYNC_OPERATION', 'Sync Operation'), ('CLEANUP', 'Cleanup Task')], max_length=30)),
                ('job_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('event', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_COMPLETED', 'Task Completed'), ('PROJECT_CREATED', 'Project Created'), ('TICKET_CREATED', 'Ticket Created'), ('TICKET_RESOLVED', 'Ticket Resolved'), ('SPRINT_STARTED', 'Sprint Started'), ('SPRINT_COMPLETED', 'Sprint Completed')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(default=dict, help_text='Custom headers as JSON')),
                ('secret_token', models.CharField(blank=True, help_text='Secret for webhook verification', max_length=255)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRY', 'Retry Scheduled')], max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField()),
                ('response_body', models.TextField(blank=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Changed'), ('ASSIGNMENT', 'Item Assigned'), ('DUE_DATE_APPROACHING', 'Due Date Approaching'), ('CREATED', 'Item Created'), ('UPDATED', 'Item Updated'), ('COMMENT_ADDED', 'Comment Added'), ('SCHEDULED', 'Scheduled Time'), ('WEBHOOK', 'Webhook Triggered')], max_length=30)),
                ('trigger_conditions', models.JSONField(default=dict, help_text='JSON conditions for trigger')),
                ('actions', models.JSONField(default=list, help_text='List of actions to execute')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, help_text='Cron expression for scheduling', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], default='SUCCESS', max_length=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('actions_executed', models.JSONField(default=list)),
                ('execution_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automation.workflowrule')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
