# Generated by Django 6.0 on 2026-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('CORE_ENGINEERING', 'Core Engineering'), ('PRODUCT_DESIGN', 'Product Design'), ('CUSTOMER_SUCCESS', 'Customer Success'), ('GENERAL', 'General')], default='GENERAL', max_length=100),
        ),
    ]
