# Generated by Django 6.0 on 2026-01-07 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_enterprise_enforce_ip_whitelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_users', models.IntegerField(default=10)),
                ('max_storage_gb', models.IntegerField(default=5)),
                ('features', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member'), ('GUEST', 'Guest'), ('EMPLOYEE', 'Employee')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member'), ('GUEST', 'Guest'), ('EMPLOYEE', 'Employee')], default='MEMBER', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='oauthconnection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='country',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='primary_color',
            field=models.CharField(default='#0052CC', max_length=7),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='secondary_color',
            field=models.CharField(default='#172B4D', max_length=7),
        ),
        migrations.AddField(
            model_name='oauthconnection',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en-us', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(default='desktop', max_length=20),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='domain',
            field=models.CharField(help_text='e.g. company.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='ip_whitelist',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed IPs'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='sso_provider',
            field=models.CharField(blank=True, choices=[('GOOGLE', 'Google'), ('OKTA', 'Okta'), ('AZURE', 'Azure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='oauthconnection',
            name='provider',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oauthconnection',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthconnection',
            name='scopes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.enterprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='EnterpriseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.enterprise')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.subscriptionplan')),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='oauthconnection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='oauthconnection',
            name='provider_data',
        ),
        migrations.RemoveField(
            model_name='oauthconnection',
            name='token_expires_at',
        ),
        migrations.RemoveField(
            model_name='oauthconnection',
            name='updated_at',
        ),
    ]
