# Generated by Django 6.0.5 on 2026-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriptionplan_remove_role_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
